---
<<<<<<< Updated upstream
- hosts: testing
=======
- hosts: nas
>>>>>>> Stashed changes
  become: yes
  
##################################################
#                       CHECK                    #
##################################################
#
  tasks:
          - name: "check lxd exists"
            shell: "which lxd | cat "
            args:
                    executable: /bin/bash

            register: lxd_result



##################################################
#                  BUILD/INSTALL                 #
##################################################


          - name: "install lxd"
            package:
                    name: lxd
                    state: present
            when: lxd_result.stdout == ""

    #- name: "Install lxd"




