---
- hosts: nas
  become: yes
  
##################################################
#                       CHECK                    #
##################################################
#
  tasks:
          - name: "check lxd exists"
            shell: "which lxd | cat "
            args:
                    executable: /bin/bash

            register: lxd_result

          - name: "check ansible exists"
            shell: "which ansible | cat "
            args:
                    executable: /bin/bash

            register: ansible_result





##################################################
#                  BUILD/INSTALL                 #
##################################################


          - name: "install lxd"
            package:
                    name: lxd
                    state: present
            when: lxd_result.stdout == ""

          - name: "install ansible"
            package:
                    name: ansible
                    state: present
            when: ansible_result.stdout == ""


    #- name: "Install lxd"




