---
- hosts: nas
  vars: 
      pkgs:
              - python2
              - libressl
              - rutorrent
              - nginx
              - rtorrent



            ##################################################
            #                       CHECK                    #
            ##################################################

  tasks:
          - name: "check lxd exists"
            register: lxd_result
            shell: "which lxd | cat "
            args:
                    executable: /bin/bash

          - name: "check seedbox exists & is running"
            register: seedbox_result
            shell: "lxc list | grep -o \'seedbox | RUNNING\' | cat"
            args:
                    executable: /bin/bash

          - name: "check if seedbox has sshd"
            register: sshd_result
            shell: "lxc exec seedbox which sshd | cat"
            args:
                    executable: /bin/bash

          - name: "check if pkgs exists in seedbox"
            register: pkg_result
            with_items: "{{ pkgs }}"
            shell: "lxc exec seedbox which {{ item }}  | cat"
            args:
                    executable: /bin/bash




                    ##################################################
                    #                  BUILD/INSTALL                 #
                    ##################################################

          - name: "create seedbox container"
            register: seedbox_result
            when: seedbox_result.stdout == ""
            lxd_container:
                    name: seedbox
                    state: started
                    source:
                            type: image
                            mode: pull
                            server: https://images.linuxcontainers.org
                            protocol: lxd
                            alias: alpine/3.8/amd64
                            profiles: ["default"]
                            wait_for_ipv4_addresses: true
                            timeout: 600

          - name: "install ssh on seedbox"
            command: "lxc exec seedbox apk add openssh"
            register: 
            when: sshd_result.stdout == ""

          - name: "install missing packages on seedbox"
            with_items: "{{ pkg_result.results }}"
            when: item.stdout == ""
            command: "lxc exec seedbox apk add {{ item.item }}"

